# ┏━━━━━━ RivalMC Core Settings ━━━━━━━┓
core:

  # Hub server name (for /hub)
  hub-lobby-name: "hub"

  # Database Connection
  mysql:
    host: "localhost"
    port: "3306"
    database: "rivalcore"
    user: "root"
    password: ""

  # Discord Guild ID for logging
  discord:
    bot-token: "MTMzMDcxMzQ2NjAyOTQ3Nzk1OQ.GqEWSH.YF0znhjs-aDdsPf9KW-KhLwTiig_WXiWycWd4g"
    logger: false
    logger-guildid: "1288892432649420811"
    rival-guildid: "1288892432649420811"
    rivalstaff-guildid: "1080070334998388837"
    security-webhook: "https://discord.com/api/webhooks/1355417161530609765/tX6GwKwEBwhlJs_TDOiFFCfDLABj-rMenmXdkmfEgHK6MZXZr3fN3Nm9Ns-ABYJYAaW5"
    leaderboard: false

  # Proxy MOTD
  motd:
    - "                <yellow>RivalMC <red>[1.8 - 1.21.X]</red>"
    - "<blue>discord.gg/rivalmc</blue> <white>|</white> <gold>store.rivalmc.net</gold>"


  # MOTD description (normal mode)
  motd-description:
    - "<yellow><bold>⭐ - RivalMC - ⭐</bold></yellow>"
    - "<yellow>Checkout our socials here!</yellow>"
    - " "
    - "<aqua>DISCORD <dark_gray>»»</dark_gray> <aqua>discord.gg/rivalmc</aqua>"
    - "<gold>STORE <dark_gray>»»</dark_gray> <gold>store.rivalmc.net</gold>"

  # Maintenance Mode Configuration
  maintenance-mode:
    status: false
    motd: "<red>❌ - ᴄᴜʀʀᴇɴᴛʟʏ ɪɴ ᴍᴀɪɴᴛᴇɴᴀɴᴄᴇ - ❌</red>"

    maintenance-motd-description:
      - "<red><bold>⭐ - RivalMC - ⭐</bold></red>"
      - "<red><bold>ᴄᴜʀʀᴇɴᴛʟʏ ɪɴ ᴍᴀɪɴᴛᴇɴᴀɴᴄᴇ!</bold></red>"
      - "<yellow>Checkout our socials here!</yellow>"
      - " "
      - "<aqua>DISCORD <dark_gray>»»</dark_gray> <aqua>discord.gg/rivalmc</aqua>"
      - "<gold>STORE <dark_gray>»»</dark_gray> <gold>store.rivalmc.net</gold>"

    # Players allowed to bypass maintenance
    bypass-players:
      - "flennnium"
      - "Yakho"
      - "lMhmd"
      - "TechnoKsa"
      - "hubailmn"
      - "ObsessiveBf_"
      - "_b78"
      - "ZNJBELL"
      - "w8o"
      - "2F5m"

  # Plugin Messages Configuration
  messages:
    prefix: "<bold><gradient:#bcbf11:#8f550a>ʀɪᴠᴀʟᴄᴏʀᴇ »</gradient></bold><reset>"
    staff-chat-prefix: "<bold><gradient:#618a0a:#8f550a>ʀɪᴠᴀʟssᴛᴀғғᴄʜᴀᴛ »</gradient></bold><reset>"
    maintenance-mode-message: "<red>ꜱᴇʀᴠᴇʀ ɪꜱ ᴄᴜʀʀᴇɴᴛʟʏ ɪɴ ᴍᴀɪɴᴛᴇɴᴀɴᴄᴇ ᴍᴏᴅᴇ</red>"
    maintenance-version-message: "<bold><dark_red>ᴍᴀɪɴᴛᴇɴᴀɴᴄᴇ</dark_red></bold>"
    alert-prefix: "<bold><green>ANNOUNCEMENT</green> <dark_gray>|</dark_gray> <reset>"
    alert-title: "<bold><green>ANNOUNCEMENT</green> <reset>"
    leaderboard-category-name: "◂〣 LEADERBOARDS 〣▸"
